name: 'Create Azure ML Online Endpoint'
description: 'Create an Azure ML Online Endpoint'
author: 'Marc van Duyn'
branding:
    icon: 'azure-logo.svg'
    color: 'blue'

inputs:
  endpointName:
    description: 'Name of the endpoint'
    required: true
  resource_group:
    description: 'Azure Resource Group'
    required: true
  workspace_name:
    description: 'Azure ML Workspace Name'
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
