name: 'Create Azure Machine Learning Online Endpoint'
description: 'Create an Azure Machine Learning Online Endpoint'
author: 'Marc van Duyn'
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  endpoint_name:
    description: 'Name of the endpoint'
    required: true
  resource_group:
    description: 'Azure Resource Group'
    required: true
  workspace_name:
    description: 'Azure ML Workspace Name'
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
